name: particular
description: "The Particular is a high performance particle effects flutter widget."
publish_to: 'none'
version: 0.2.0
homepage: https://manjav.github.io/particular/editor/web
repository: https://github.com/manjav/particular
issue_tracker: https://github.com/manjav/particular/issues
documentation: https://github.com/manjav/particular

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  image: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# screenshots:
#   - description: 'LineChartSample1 and LineChartSample2'
#     path: pub_screenshots/line_chart.jpg

topics:
  - particle
  - particles
  - visualization
  - game
  - effects